apiVersion: v2
name: webui
description: Chronicle WebUI
version: 0.1.0
appVersion: "1.0"
keywords:
  - chronicle
  - webui
  - frontend
sources:
  - https://github.com/BasedHardware/Friend
home: https://github.com/BasedHardware/Friend

